Create wrapper structs and interfaces for properties data structures and payloads
unicode-org/icu4x pull request #1333
Opened 2021-11-19 21:29 UTC by echeran

Fixes #1239

2021-11-19 21:54 UTC, sffc requested changes
Also, please remove the 4th commit from this PR.

2021-11-19 21:54 UTC, sffc commented on CODEOWNERS
> +components/codepointset/          echeran @iainireland
Please restore yourself

2021-11-19 21:54 UTC, sffc commented on .github/workflows/build-test.yml
> +          - utils/codepointset
Reminder to update the gh_pages branch

2021-11-19 21:54 UTC, sffc commented on docs/process/prd.md
> +-   Introduce a low-level foundation for string operations with [UnicodeSet](https://docs.rs/icu_codepointset/0.1.0/icu_codepointset/)
Suggestion: Change this to go to icu_uniset/0.1.0

2021-11-19 21:54 UTC, sffc commented on docs/process/prd.md
> +ICU4X offers an environment in which we are developing a new Unicode UAX#14/UAX#29 compatible segmentation API which will use the foundational [CodePointSet API](https://docs.rs/icu_codepointset/0.1.
Either revert or link to the staging docs

2021-11-19 21:54 UTC, sffc commented on docs/tutorials/writing_a_new_data_struct.md
> +- `icu::codepointset::provider::UnicodePropertyV1`
Nit: This should be icu::properties anyway

2021-11-19 21:54 UTC, sffc commented on utils/codepointset/src/lib.rs
> +//! It is an implementation of the existing [ICU4C CodePointSet API](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1CodePointSet.html).
Nit: This one should not change

2021-11-19 22:07 UTC, sffc commented on components/properties/src/api_util.rs
> +    fn iter_ranges(&self) -> Vec<u32> {
This becomes `-> Self::Iter`

2021-11-19 22:07 UTC, sffc commented on components/properties/src/api_util.rs
> +impl CodePointSetLike for CodePointSetData {
Add the fully qualified iterator type here

2021-11-19 22:07 UTC, sffc commented on components/properties/src/lib.rs
> +extern crate alloc;
Don't forget to delete this after removing the Vec

2021-11-19 22:07 UTC, sffc commented on components/properties/src/api_util.rs
> +pub trait CodePointSetLike {
Issue: This trait should be in `icu_codepointset`

2021-11-19 22:20 UTC, sffc requested changes

2021-11-19 22:20 UTC, sffc commented on .github/workflows/build-test.yml
> +          - utils/codepointset
Actually, let's NOT change the crate name.  Only change the type name

2021-11-19 22:23 UTC, sffc commented on components/icu/src/lib.rs
> +    //! ## Property data as `CodePointSet`s
As discussed: CodePointInversionList

2022-08-09 23:06 UTC, echeran commented
Closing this old draft PR because it has been superseded by the subsequent proper design work and PRs #2112 and #2140 and other related PRs.

2022-08-09 23:06 UTC, closed without merging