fix error in From of MetaZoneSpecificNamesV1
unicode-org/icu4x pull request #1405
Opened 2021-12-16 00:28 UTC by samchen61661

Fix an error in From of MetaZoneSpecificNamesV1.

We want to remove `generic` key but map size should not be larger than 1.

2021-12-16 00:31 UTC, nordzilla submitted a review, later dismissed
Thanks for fixing this!

2022-01-06 17:04 UTC, nordzilla approved these changes

2022-01-07 19:41 UTC, sffc submitted a review, later dismissed

2022-01-07 23:36 UTC, nordzilla approved these changes

2022-01-07 23:37 UTC, nordzilla requested changes
@samchen61661 

It looks like the most recent rebase accidentally added some `.idea` files.

2022-01-08 00:06 UTC, nordzilla approved these changes

2022-01-08 00:39 UTC, merged