Using rust_link in FFI
unicode-org/icu4x pull request #1786
Opened 2022-04-08 00:11 UTC by robertbastian

2022-04-08 07:00 UTC, robertbastian commented
Hmm I manually validated all URLs and found a typo and one that was out of date. Maybe the Diplomat tool could check that the URLs are 200s?

2022-04-08 16:50 UTC, Manishearth commented
>  Maybe the Diplomat tool could check that the URLs are 200s?

Strongly against a codegen tool hitting the network. As a separate linkcheck tool, maybe, but it's unexpected when such tools hit the network.

2022-04-08 17:05 UTC, robertbastian commented
It could be a `HEAD` request behind a flag

2022-04-08 17:31 UTC, sffc commented
It looks like you update the `diplomat` version. Look in `ffi/diplomat/Cargo.toml` and change the sha of diplomat.

2022-04-08 18:39 UTC, Manishearth commented
Also the rust_link support is broken in diplomat and https://github.com/rust-diplomat/diplomat/pull/138 needs to land first

2022-04-12 21:09 UTC, sffc reviewed
(setting review bit)

2022-04-12 21:33 UTC, Manishearth approved these changes

2022-04-12 21:37 UTC, Manishearth requested changes

2022-04-12 21:37 UTC, Manishearth commented on ffi/diplomat/diplomat_gen_all.sh
> +diplomat-tool c ./c/include --docs-base-urls=icu:https://unicode-org.github.io/icu4x-docs/doc/ --docs-base-urls=fixed_decimal:https://unicode-org.github.io/icu4x-docs/doc/ --docs-base-urls=icu_plural
issue: I'd rather not do this, this is brittle

As I'd proposed [here](https://github.com/rust-diplomat/diplomat/pull/136#discussion_r835496570), can we have a single "default" parameter for the doc base URL? we could continue to allow for passing in additional stuff. And we can special case `docs.rs` to mean "link to docs.rs with the correct format"

2022-04-27 09:29 UTC, Manishearth approved these changes

2022-04-27 10:07 UTC, merged