testdata download to icu_testdata, no Cargo.toml parsing
unicode-org/icu4x pull request #1812
Opened 2022-04-22 13:08 UTC by robertbastian

2022-04-26 14:36 UTC, robertbastian commented on provider/testdata/data/cldr/cldr-core/supplemental/metaZones.json
> +      "_cldrVersion": "40"
This was included manually in #1782, I've added it to the CLDR_JSON_GLOB and reran the download.

2022-04-26 15:26 UTC, sffc requested changes

2022-04-26 15:26 UTC, sffc commented on provider/testdata/Cargo.toml
> -[package.metadata.icu4x_testdata]
As discussed: I prefer these settings to be data-driven.

2022-04-27 09:32 UTC, Manishearth approved these changes

2022-04-27 09:32 UTC, Manishearth commented on provider/testdata/README.md
> +- `cargo make testdata-download-sources` downloads fresh CLDR JSON
praise: good call on naming

2022-04-27 11:32 UTC, sffc approved these changes

2022-04-27 11:40 UTC, merged