Implement formatting for fractional seconds
unicode-org/icu4x pull request #1813
Opened 2022-04-22 18:45 UTC by dminor

Fixes #485

2022-04-25 18:03 UTC, gregtatum requested changes
I'm marking request changes for 3 reasons:

1. Potential arithmetic overflow for the API `FieldLength::Fixed(n)`
2. No max field size enforced from the parsed pattern, which I believe could lead to arithmetic overflow as well.
3. The `unimplemented` panics.

2022-04-26 13:52 UTC, dminor commented on components/datetime/src/pattern/reference/parser.rs
> +                        FieldLength::Fixed(2),
Writing the test here was important for me to be able to debug and understand the parsing behaviour. I hate to remove a test once written, which is why I left it here.

2022-04-26 14:23 UTC, dminor commented on components/datetime/tests/patterns/tests/dayperiods.json
> +              "h:mm:ss.SSSSSSSSSSS"
There's a place for testing errors in parser.rs. I've added a test there. Here I'll put a test for 127 `S`, the largest the implementation supports without generating an error.

2022-04-26 19:17 UTC, gregtatum commented on components/datetime/src/pattern/reference/parser.rs
> +                        FieldLength::Fixed(2),
Sorry, I wasn't clear in what I was saying. I'm happy to keep this test here. 👍 I too find these types of tests useful for debugging.

2022-04-26 19:18 UTC, gregtatum approved these changes
Thanks for fixing the overflows and panics, this looks good to me now 👍

2022-04-26 22:57 UTC, merged