Datagen API
unicode-org/icu4x pull request #1819
Opened 2022-04-27 09:30 UTC by robertbastian

Part of #1188

2022-04-27 10:17 UTC, Manishearth commented on provider/datagen/Cargo.toml
> +default-run = "icu4x-datagen"
TIL!

2022-04-27 12:28 UTC, sffc commented on provider/datagen/src/lib.rs
> +pub enum Out {
Praise: I like this abstraction

2022-04-27 14:37 UTC, Manishearth approved these changes

2022-04-27 14:37 UTC, Manishearth commented on provider/datagen/src/lib.rs
> +/// * `out`: See the documentation on [`Out`]
nit: should probably still say something like "details on the output format and location. see documentation on Out"

2022-04-27 14:42 UTC, robertbastian commented on provider/datagen/src/lib.rs
> +    /// Output as a postcard blob to the given sink.
Yeah we don't do JSON blobs

2022-04-27 15:49 UTC, Manishearth submitted a review, later dismissed

2022-04-27 21:05 UTC, sffc requested changes
LGTM overall, just some small things

2022-04-27 21:05 UTC, sffc commented on provider/datagen/src/transform/cldr/serde/aliases.rs
> +    pub language_aliases: LiteMap<String, Replacement<String>>,
Praise (here and elsewhere): thanks for fixing this

2022-04-27 21:05 UTC, sffc commented on provider/datagen/src/transform/cldr/serde/numbers.rs
> +    #[serde(deserialize_with = "serde_aux::prelude::deserialize_number_from_string")]
Praise: good idea

2022-04-27 21:05 UTC, sffc commented on provider/datagen/src/transform/uprops/enum_uniset.rs
> +/// A data provider reading from TOML files produced by the ICU4C icuwriteuprops tool.
Nit:
```suggestion
/// A data provider reading from TOML files produced by the ICU4C icuexportdata tool.
```

2022-04-27 21:05 UTC, sffc commented on provider/datagen/src/transform/uprops/mod.rs
> +//! ICU4C icuwriteuprops tool.
Nit (here and elsewhere): I know this is pre-existing but the tool is named "icuexportdata" not "icuwriteuprops" (this was an older name for the tool when it was being drafted)

2022-04-27 21:05 UTC, sffc commented on provider/datagen/src/transform/uprops/script.rs
> +/// A data provider reading from TOML files produced by the ICU4C icuwriteuprops tool.
Nit: `icuexportdata`

2022-04-28 09:28 UTC, sffc approved these changes

2022-04-28 09:29 UTC, merged