Merge datagen "reader" modules
unicode-org/icu4x pull request #1854
Opened 2022-05-04 13:42 UTC by sffc

Cleanup that we can do now that `cldr` and `uprops` are in the same crate

2022-05-04 14:08 UTC, robertbastian commented
Thought: move this logic into `SourceData` instead of a reader module. This would get us closer to caching in there.

2022-05-05 09:22 UTC, robertbastian requested changes
^

2022-05-05 11:07 UTC, sffc commented
I would like to merge this as-is because it is a small positive change (deduplicating code) and it slightly cleans up #1839.

2022-05-05 11:41 UTC, robertbastian approved these changes

2022-05-05 11:42 UTC, merged