Add segmenter dictionary data to testdata.
unicode-org/icu4x pull request #2135
Opened 2022-06-28 23:42 UTC by makotokato

I would like to move segmenter dictionaries to testdata. These TOML files are converted from binary files although testdata doesn't include Khmer, Lao and Burmese.

Although dictionary segmenter key/structure of this fix is the following by locale, please suggest me about better key/structure.
- segmenter/dictionary@1
  - ja (Chinese and Japanese)
  - km
  - lo
  - my
  - th

2022-06-29 00:49 UTC, sffc reviewed
This looks good. Just a few small comments. I will think more about how to handle the multiple languages.

2022-06-29 00:49 UTC, sffc commented on experimental/segmenter/src/dictionary.rs
> +        let payload = get_payload("ja").unwrap();
This is a good question (how to represent the CJK dictionary as a language tag). Let me think about it more.

2022-06-29 00:49 UTC, sffc commented on experimental/segmenter/src/line.rs
> +            .map_err(|_| DataError::custom("cannot parse locale string"))?;
Suggestion, here and elsewhere: use the macro (which expands to a const function)

```suggestion
        let locale = locale!("th");
```

2022-06-29 00:49 UTC, sffc commented on provider/datagen/src/transform/segmenter/mod.rs
> +                )?)?;
Suggestion: make `get_toml_filename` return `Option<&'static str>`, and then do

```suggestion
                .read_and_parse_toml::<SegmenterDictionaryData>(Self::get_toml_filename(
                    &req.options,
                ).ok_or_else(|| DataErrorKind::MissingResourceOptions.with_req(UCharDictionaryBreakDataV1Marker::KEY, req))?)?;
```

and then you can remove the redundant `if req.options.get_langid() == ...` condition in this function.

Note that you should be returning `DataErrorKind::MissingResourceOptions`, not `DataError::custom`

2022-06-29 00:49 UTC, sffc commented on provider/datagen/src/transform/segmenter/mod.rs
> +        Ok(r)
Suggestion: this whole function can be written as
```suggestion
        Ok(vec![locale!("th"), locale!("km"), locale!("lo"), locale!("my"), locale!("ja")])
```

2022-06-29 10:01 UTC, robertbastian requested changes

2022-07-07 09:08 UTC, robertbastian requested changes
Looks good, just some nits.

I'd also recommend naming this PR "Add segmenter dictionary data to datagen", it ends up in testdata as a result of that.

2022-07-07 09:08 UTC, robertbastian commented on experimental/segmenter/src/word.rs
> +            .map_err(|_| DataError::custom("cannot parse locale string"))?;
macro

2022-07-07 14:20 UTC, makotokato commented on experimental/segmenter/src/dictionary.rs
> +            .map_err(|_| DataError::custom("Cannot parse locale string"))?;
Thanks, I use `get_payload(locale!("ja")`.

2022-07-07 19:01 UTC, robertbastian approved these changes

2022-07-07 22:55 UTC, merged