Add ExactSizeIterator
unicode-org/icu4x pull request #2580
Opened 2022-09-19 07:55 UTC by pdogr

This PR adds ExactSizeIterator to FlexZeroVec, ZeroMap.

2022-09-19 11:12 UTC, robertbastian requested changes

2022-09-19 11:12 UTC, robertbastian commented on utils/zerovec/src/map/map.rs
> +    > + ExactSizeIterator<
ExactSizeIterator extends Iterator, so you don't have to list both.

2022-09-19 13:24 UTC, robertbastian approved these changes

2022-09-19 13:59 UTC, merged

2022-09-23 05:34 UTC, sffc reviewed
lgtm