bump simple_logger to 4.1.0
unicode-org/icu4x pull request #3337
Opened 2023-04-17 09:10 UTC by pdogr

Running the command 

`cargo run --release --bin=icu4x-datagen --all-features -- --icuexport-root=provider/repodata/data/icuexport --syntax=postcard --out=/tmp/icu4x_data --overwrite --keys=segmenter/word@1 --all-locales`

leads to the following error 
```
thread 'main' panicked at 'Could not determine the UTC offset on this system. 
Possible causes are that the time crate does not implement "local_offset_at" on your system, 
or that you are running in a multi-threaded environment and the time crate is returning "None" from "local_offset_at" to avoid unsafe behaviour.
```

Bumping simple_logger to latest fixes this 
https://github.com/borntyping/rust-simple_logger/issues/48#issuecomment-1016774867

2023-04-17 09:44 UTC, robertbastian commented
#3338

2023-04-17 10:48 UTC, robertbastian commented
There's a third usage in `ffi/diplomat`.

We should probably merge and release #3339 first

2023-04-17 16:04 UTC, Manishearth submitted a review, later dismissed

2023-04-18 09:16 UTC, robertbastian requested changes
^

2023-04-18 10:04 UTC, robertbastian approved these changes

2023-04-18 11:18 UTC, merged

2023-04-20 15:40 UTC, sffc reviewed
lgtm