feat: add UTF16 benchmarks in normalizer
unicode-org/icu4x pull request #3372
Opened 2023-04-21 09:51 UTC by dsipasseuth

Adding UTF16 benches

#2444

2023-05-12 12:09 UTC, robertbastian requested changes

2023-05-12 12:09 UTC, robertbastian commented on components/normalizer/benches/composing_normalizer_nfc.rs
> +    data_utf16
```suggestion
    s.encode_utf16().collect()
```

Also consider inlining.

2023-05-26 12:48 UTC, dsipasseuth commented on components/normalizer/benches/composing_normalizer_nfc.rs
> +    data_utf16
done!

2023-05-26 12:55 UTC, robertbastian approved these changes

2023-05-30 19:17 UTC, merged