Fixed Gregorian calendar overflows
unicode-org/icu4x pull request #3466
Opened 2023-05-31 17:58 UTC by sotam1069

Decide on overflow behavior for calendar arithmetic https://github.com/unicode-org/icu4x/issues/2151

2023-05-31 23:15 UTC, echeran commented on components/calendar/src/gregorian.rs
> +    /// ```rust
Run `cargo fmt` to make the CI job pass. It likes to remove trailing whitespace at the end of lines.

2023-05-31 23:15 UTC, echeran commented on components/calendar/src/gregorian.rs
> +
Remove blank line between `#[...]` line and the following line that it applies to.

2023-05-31 23:15 UTC, echeran commented on components/calendar/src/gregorian.rs
> +        //Compares the next_year variable to i32::MAX to check for overflow
```suggestion
        // Compares the next_year variable to i32::MAX to check for overflow
```

2023-05-31 23:15 UTC, echeran commented on components/calendar/src/gregorian.rs
> +        //Compares the prev_year variable to i32::MIN to check for overflow
```suggestion
        // Compares the prev_year variable to i32::MIN to check for overflow
```

2023-05-31 23:15 UTC, echeran commented on components/calendar/src/gregorian.rs
> +    fn day_of_year_info_overflow(){
Space between the `()` and the `{`. The formatter will probably make that change.

2023-05-31 23:15 UTC, echeran commented on components/calendar/src/gregorian.rs
> +        assert_eq!(Calendar::day_of_year_info(&Gregorian, &date_max.inner).next_year.number,i32::MAX,);
(formatting again) Trailing comma inside parens.

2023-06-01 22:01 UTC, sffc requested changes

2023-06-01 22:01 UTC, sffc commented on components/calendar/src/iso.rs
>      fn day_of_year_info(&self, date: &Self::DateInner) -> types::DayOfYearInfo {
Issue: don't have iso.rs changes in this PR

2023-06-02 21:40 UTC, echeran submitted a review, later dismissed
LGTM

2023-06-02 21:45 UTC, sffc requested changes

2023-06-02 21:45 UTC, sffc commented on components/calendar/src/gregorian.rs
> +                case.prev_year.saturating_neg(),
Nit: If you always call `.saturating_neg()` on `case.prev_year`, then you should just represent `prev_year` in that form in the test case (as a positive year number).

2023-06-02 21:45 UTC, sffc commented on components/calendar/src/gregorian.rs
> +                prev_year: i32::MIN,
Nit: Add at least one cases that does not saturate

2023-06-02 23:12 UTC, sffc requested changes

2023-06-02 23:12 UTC, sffc commented on components/calendar/src/gregorian.rs
> +            number: year.saturating_sub(0),
Issue: This is definitely different behavior. This is not correct. The year is being projected into BCE so it should be 1 - year. Please change back to what you had before, and fix the tests.

2023-06-03 00:43 UTC, sffc approved these changes

2023-06-03 03:50 UTC, merged

2023-06-03 14:55 UTC, Manishearth reviewed
post-merge review: lgtm!