Add Ord on locale related structs
unicode-org/icu4x pull request #3588
Opened 2023-06-27 20:08 UTC by bbqsrc

Adds `Ord` to Locale related structs so a `Locale` can be used as a key in a `BTreeMap`.

2023-06-27 20:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unicode-org/icu4x?pullRequest=3588) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unicode-org/icu4x?pullRequest=3588) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unicode-org/icu4x?pullRequest=3588) it.</sub>

2023-06-27 21:45 UTC, sffc commented
Hi! Please take a look at https://github.com/unicode-org/icu4x/issues/1215

2023-06-27 22:01 UTC, bbqsrc commented
Okay, cool. I half expected this might be the case but couldn’t find it.

The problem is, it wasn’t resolved and instead simply removed. Lexicological ordering of keys is sufficient, and adding subjective bias to what are ultimately string markers for a locale and its configuration is at the very least interesting but not particularly useful.

What is the path forward?

2023-06-28 01:39 UTC, sffc requested changes
I still think that loc1.cmp(loc2) should equal loc1.to_string().cmp(loc2.to_string()). That's fairly easy for language identifiers and somewhat harder but not infeasible for extensions.

2023-06-28 07:33 UTC, bbqsrc commented
That is a path forward. 🙂

2023-07-27 18:14 UTC, sffc commented
Closing for now, but we're still open to an Ord impl in accordance with the issues above.

2023-07-27 18:14 UTC, closed without merging