Making baked providers private where possible
unicode-org/icu4x pull request #3939
Opened 2023-08-25 14:22 UTC by robertbastian

The two crates where this is not currently possible are:
* `icu_properties`: `icu_unicodesetparser` dynamically loads property sets during parsing. We'd need to store the provider internally as an Option and then call the baked constructors if we don't have a provider.
* `icu_normalizer`: `icu_collator` depends on this, and needs to be rewritten to use public APIs

2023-08-25 16:51 UTC, sffc requested changes

2023-08-25 16:51 UTC, sffc commented on components/datetime/tests/datetime.rs
> -                });
Issue: These are very important tests and we must keep them working.

2023-08-25 16:51 UTC, sffc commented
Did we discuss this before? What is the motivation for this change?

We already define anything in the `provider` module as "unstable, use at your own risk". I think there is potential value in having the flexibility to use `provider::Baked` in client code and I'd rather not close the door on that.

2023-08-25 19:48 UTC, robertbastian commented
The motivation is you wanting to make these part of the advertised API in https://github.com/unicode-org/icu4x/issues/3935

2023-08-25 19:50 UTC, robertbastian commented
We also already decided that a crate should *not* use another crate's baked provider, and this PR cleans up one of the cases that does.

Integration tests should really also not use unstable providers, they should either use the compiled data API, or define their own provider.

2023-08-25 19:55 UTC, sffc commented
I think we're not aligned on some of the fundamentals here. We should discuss.

2023-09-05 18:41 UTC, sffc commented
Discussion: change this to instead document the APIs as being unstable (with the slab block). They are unstable because the traits implemented on `provider::Baked` could change or be removed over time.

2023-09-06 19:46 UTC, sffc approved these changes

2023-09-06 19:46 UTC, sffc commented
The CI failures seem to be crates.io being flaky again

2023-09-06 21:14 UTC, merged