Move neo months over to a linear-only model
unicode-org/icu4x pull request #4217
Opened 2023-10-24 22:58 UTC by Manishearth

In this model, month codes are not used for indexing; rather we just use the month number, and have a `LeapLinear` variant in the symbols data enum that basically has the regular month codes in order followed by the leap month codes. Once this lands I'll update https://github.com/unicode-org/icu4x/pull/4212 touse this, and also generate LeapLinear data for Chinese/Dangi.

2023-10-24 23:07 UTC, sffc requested changes

2023-10-24 23:07 UTC, sffc commented on provider/datagen/src/transform/cldr/datetime/neo.rs
> +            symbols[index] = &**v;
This doesn't work; please fix. You are currently generating this JSON. Note that CLDR-JSON month numbering for Hebrew is a complete mess.

```json
  "LeapLinear": [
    "Tishri",
    "Heshvan",
    "Kislev",
    "Tevet",
    "Shevat",
    "Adar I",
    "Adar",
    "Nisan",
    "Iyar",
    "Sivan",
    "Tamuz",
    "Av",
    "Elul",
    "",
    "",
    "",
    "",
    "",
    "Adar II",
    "",
    "",
    "",
    "",
    ""
  ]
```

2023-10-24 23:09 UTC, sffc commented on provider/datagen/src/transform/cldr/datetime/neo.rs
> +            symbols[index] = &**v;
Note that the old logic uses this table to map from CLDR-JSON Hebrew month codes to Temporal month codes:

```rust
    static HEBREW_MONTH_CODES: &[TinyStr4] = &[
        tinystr!(4, "M01"),
        tinystr!(4, "M02"),
        tinystr!(4, "M03"),
        tinystr!(4, "M04"),
        tinystr!(4, "M05"),
        tinystr!(4, "M05L"),
        tinystr!(4, "M06"),
        tinystr!(4, "M07"),
        tinystr!(4, "M08"),
        tinystr!(4, "M09"),
        tinystr!(4, "M10"),
        tinystr!(4, "M11"),
        tinystr!(4, "M12"),
        // M06L is handled separately in MonthSymbols code
    ];
```

2023-10-25 18:38 UTC, Manishearth commented
Went ahead and included the pattern stuff for chinese here rather than having it go in https://github.com/unicode-org/icu4x/pull/4212, now #4212 will be used for the numeric stuff only (it doesn't have the code for that yet)

2023-10-25 19:42 UTC, sffc requested changes

2023-10-25 19:42 UTC, sffc commented on provider/datagen/src/transform/cldr/datetime/neo.rs
> +                symbols[nonleap + i] = replaced.into();
Skip months that are empty?

2023-10-25 19:42 UTC, sffc commented on provider/datagen/src/transform/cldr/datetime/neo.rs
> +                }
Should be -1 not +1 I think. The JSON file is still wrong.

2023-10-25 19:42 UTC, sffc commented on provider/datagen/src/transform/cldr/datetime/neo.rs
> +        if has_leap {
Thought: Somewhat confusing because this is really `if has_leap && calendar != "hebrew"` since we're inside a nested if statement

2023-10-25 20:01 UTC, Manishearth commented
data regen still wip

2023-10-25 20:13 UTC, sffc approved these changes

2023-10-25 20:37 UTC, Manishearth commented
autosubmit=on

2023-10-25 20:58 UTC, sffc approved these changes

2023-10-25 21:01 UTC, merged