Bumping versions to 1.4
unicode-org/icu4x pull request #4320
Opened 2023-11-16 17:48 UTC by robertbastian

2023-11-16 21:00 UTC, sffc approved these changes

2023-11-16 22:05 UTC, sffc requested changes
Blocking 1.4 until we achieve agreement on https://github.com/unicode-org/icu4x/pull/4321

2023-11-16 22:54 UTC, robertbastian commented on provider/baked/compactdecimal/Cargo.toml
> +version.workspace = true
yes this file is a mistake

2023-11-16 23:12 UTC, robertbastian commented
https://github.com/unicode-org/icu4x/pull/4320

2023-11-16 23:41 UTC, robertbastian commented on CHANGELOG.md
>  ## Unreleased
I'd rather do this than have the next person add it? Also it's nice to see that nothing is unreleased, everything is published!

2023-11-16 23:42 UTC, sffc approved these changes
Un-blocking the release.

2023-11-16 23:45 UTC, merged

2023-11-17 00:14 UTC, sffc commented on CHANGELOG.md
>  ## Unreleased
It looks confusing as if everything below it is unreleased. It's easy to overlook the levels of nesting.