Add CartableOptionPointer and helpers to the yoke crate
unicode-org/icu4x pull request #4449
Opened 2023-12-13 09:41 UTC by sffc

Split from #4442

I do think this is in scope for `yoke` because the type can be a "one-way" type that is a more efficient cart than either `Option<Rc<T>>` or `Option<ErasedRcCart>`.

2023-12-13 17:04 UTC, Manishearth requested changes
I'm opposed to this, for a bunch of reasons

Firstly, I think the use case here is rather specific; I don't think it's something that makes a lot of sense for most yoke users overall. If we get asks for something like this I'd like to design it based on the asks rather than genericizing the thing that ICU4X needs in a particular direction and assuming that that direction is what is needed.


Secondly, the abstraction itself is incredibly generic in a way that is both rather hard to understand  for users (IMO) and rather hard to grapple with the safety of. I think we're introducing a lot of concepts here that interact in subtle ways.

(For this to land it is going to need a _lot_ more careful documentation of the safety needs)

2023-12-13 17:42 UTC, sffc commented
> Firstly, I think the use case here is rather specific; I don't think it's something that makes a lot of sense for most yoke users overall. If we get asks for something like this I'd like to design it based on the asks rather than genericizing the thing that ICU4X needs in a particular direction and assuming that that direction is what is needed.

I don't agree that it is ICU4X-specific. This new cart type `OptionCartablePointer` is another in-house cart abstraction, like `ErasedRcCart`, which is better than any of the other cart abstractions being offered. This is especially true because we already have a lot of code specializing over both `Rc` and `Option` carts, so we clearly have already put a stake in the ground that we expect `Option<Rc>` to be a cart we expect people to want when they are using Yoke.

> Secondly, the abstraction itself is incredibly generic in a way that is both rather hard to understand for users (IMO) and rather hard to grapple with the safety of. I think we're introducing a lot of concepts here that interact in subtle ways.

Almost all of the unsafety is encapsulated in the new `CartablePointerLike` trait. I do not think it is too generic. In fact it turns out that there actually are not very many safety invariants at play; at the end of the day this type is just an efficient way to store the "raw" representation of pointer-like types (reference, Box, Rc, and Arc).

> (For this to land it is going to need a _lot_ more careful documentation of the safety needs)

Would like to pair with you today on writing the documentation.

2023-12-13 22:15 UTC, Manishearth reviewed
code looks good, minor issues around docs and examples

2023-12-13 22:15 UTC, Manishearth commented on utils/yoke/src/cartable_ptr.rs
> +// Safety: logically an Option<C>. Has same bounds as Option<C>
nit:  with my other PR landing you can potentially relate to the invariants specified there

2023-12-15 23:38 UTC, Manishearth approved these changes

2023-12-15 23:57 UTC, merged