Move tutorials, rename docs
unicode-org/icu4x pull request #4694
Opened 2024-03-15 15:51 UTC by robertbastian

Fixes #4569

2024-03-15 16:16 UTC, Manishearth approved these changes

2024-03-15 18:56 UTC, sffc approved these changes

2024-03-15 18:59 UTC, sffc requested changes
Looks like `documents` to `docs` was a bit too aggressive

2024-03-15 18:59 UTC, sffc commented on .github/workflows/artifacts-build.yml
> +        gsutil -m cp -r ffi/npm/documents/* gs://${{ env.GCP_MAIN_BUCKET_ID }}/gha/tsdoc
This should still be `docs`

2024-03-15 18:59 UTC, sffc commented on CODEOWNERS
> +# Format of the file follows: https://git-scm.com/documents/gitattributes
`docs`

2024-03-15 18:59 UTC, sffc commented on documents/process/prd.md
> +-   [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/documents/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)
`docs`

2024-03-15 18:59 UTC, sffc commented on documents/process/prd.md
> +It is required for DateTimeFormat, and will exercise our ability to maintain modularity and lean profile of our APIs, while building a large feature set that [ECMA-402 NumberFormat](https://developer
`docs`

2024-03-15 18:59 UTC, sffc commented on documents/process/prd.md
> +Collation is one of the core [ECMA-402 components](https://developer.mozilla.org/en-US/documents/Web/JavaScript/Reference/Global_Objects/Intl/Collator), and builds on top of the Unicode Properties AP
`docs`

2024-03-15 18:59 UTC, sffc commented on documents/proposals/pr001-ecma402.md
> +[ecma402]: https://developer.mozilla.org/en-US/documents/Web/JavaScript/Reference/Global_Objects/Intl
`docs`

2024-03-15 18:59 UTC, sffc commented on documents/proposals/pr002-hunkspace.md
> +XPI](https://developer.mozilla.org/en-US/documents/Mozilla/XPI) works with
`docs`

2024-03-15 18:59 UTC, sffc commented on documents/research/datetime.md
> +In ICU4X 0.1 we introduce a `DateTimeFormat` API for formatting date and time into human readable formats. That API is shaped after [`ICU4C`](http://userguide.icu-project.org/formatparse/datetime), [
`docs`

A lot of these are on developer.mozilla.org. I won't leave any more comments for these. Please do a global search and replace.

2024-03-15 18:59 UTC, sffc commented on documents/research/datetime.md
> +One example of an API that is being meticulously designed to handle the scope correctly is [EcmaScript Temporal Proposal](https://tc39.es/proposal-temporal/documents/index.html). We encourage everyon
`docs`

2024-03-19 15:39 UTC, merged

2024-03-26 02:51 UTC, sffc commented
Missed a few: https://github.com/unicode-org/icu4x/pull/4734

2024-03-26 03:34 UTC, sffc commented
Also broke WASM demo: https://github.com/unicode-org/icu4x/pull/4737