Fix deploying memory benchmarks to GitHub pages
unicode-org/icu4x pull request #472
Opened 2021-02-01 23:00 UTC by gregtatum

I didn't have a way to easily test this in a separate branch, so I ended
up missing the instructions to transfer the uploaded artifact to GitHub
pages.

2021-02-05 05:54 UTC, echeran requested changes
Even though you didn't change these lines in this PR, can you make changes that are similar to the `benchmark` job:

* make the `memory` job depend on the `build` job. (this keeps us attempting to run memory benchmarks if we can't build)
* re-use the `unmerged-pr-bench-data` branch for the GH Action to store its historical commits instead of needing a separate one (`unmerged-pr-memory-data`). There shouldn't be race condition problems because all of the data per-{component/example, benchmark-type} are all stored in distinct locations in the filesystem, so git commits only create merges and not conflicts.
* also: make the `doc_gh_pages` job also depend on the `memory` job to ensure that the copy to GH pages occurs after the memory benches are all done.  GH now has [a flowchart of all the jobs in a GH Actions workflow](https://github.com/echeran/icu4x/actions/runs/539466271), so you can mentally picture the changes, too.

Otherwise, everything looks good. I did a quick test in my personal fork. Here is an example of the result: https://echeran.github.io/icu4x-docs/benchmarks/memory/macos-latest/

Testing in the personal fork wasn't too complicated, and follows the [instructions doc](https://github.com/unicode-org/icu4x/blob/master/docs/process/ci_build.md). Should the testing instructions be improved and/or made clearer?

Here's what I did:
1. create a testing branch that tacks on [an extra commit to make testing-appropriate changes](https://github.com/echeran/icu4x/pull/22/commits/538176500f54594cffa1844c0244c7135ea24b84)
2. push the testing branch to the personal fork of `icu4x` and create a [testing PR targeting personal fork's master](https://github.com/echeran/icu4x/pull/22)
3. watch [GH Actions execute b/c of testing PR satisfying the execution trigger conditions](https://github.com/echeran/icu4x/actions/runs/539462550)
4. extra step - merge the testing PR to get GH Actions [execute the job that copies GH pages over to the fork of the docs repo](https://github.com/echeran/icu4x/actions/runs/539466271)

2021-02-05 22:04 UTC, gregtatum commented
> make the memory job depend on the build job. (this keeps us attempting to run memory benchmarks if we can't build)

I somewhat disagree. The memory benchmark is completely independent, and the current behavior parallelizes the task. In my personal tests I found this sped up the overall job run. However, I'm not opposed to it if you feel the savings in machine time is worth it.

> also: make the doc_gh_pages job also depend on the memory job

Ah, this is a oversight, thanks for the find.

> Testing in the personal fork wasn't too complicated, and follows the instructions doc.

I tested everything in a personal fork, except for the merging into master. I was a bit scared of publishing to the real GitHub pages. I see now how you commented things out and created your own repo to do it.

> Should the testing instructions be improved and/or made clearer?

It might be worth cutting down the volume of docs. They seem to re-document a lot of things that are available in the GitHub documentation. It might be worth a small paragraph with a simple bullet point list on the basics of testing the PR-flow, and the merging flow.

2021-02-05 22:13 UTC, gregtatum commented
> Should the testing instructions be improved and/or made clearer?

Oh, and I would prefer to have all of the actions documented in the `.yml` file, rather than a separate markdown file that I might now check.

2021-02-08 16:29 UTC, gregtatum commented
Working PR workflow: https://github.com/gregtatum/icu4x/actions/runs/548511543

2021-02-08 18:00 UTC, echeran commented
> Working PR workflow: https://github.com/gregtatum/icu4x/actions/runs/548511543

Nice! And I don't think this will affect the overall wall clock time of the CI run because we only have 5 slots for simultaneous execution in GH Actions as an open source repo, and as that workflow instance link shows, overall time is greatly dominated by the `features` job.

I'll update the CI markdown doc a little to be clearer and more concise. I agree, the action-specific details are best kept in the *.yml workflow files and thorough enough to be reproducible. The *.md file on CI in the repo is meant to be a high-level intro so that people completely new to CI and/or GH Actions can replicate in other repos in unicode-org, so it summarizes the details of *.yml files but also errs on the side of redundant in order to be more self-contained.

2021-02-08 19:06 UTC, gregtatum commented
Here is the "merge to master" - https://github.com/gregtatum/icu4x/actions/runs/548576714

It skipped the deploy to Github pages because it was run on a fork:

> This action runs on a fork and not found auth token, Skip deployment

But it looks like the gh-pages branch has the new information: https://github.com/gregtatum/icu4x/tree/gh-pages

> overall time is greatly dominated by the features job

Ah, yes this is true. When I was working on this, I disabled that job for fast feedback on my changes.

2021-02-08 19:41 UTC, echeran approved these changes
Looks good!

These are the steps that you can follow to setup the tokens for cross-repo authentication in your personal forks of `icu4x` and `icu4x-docs` for the job that copies over the GH pages:
https://github.com/unicode-org/icu4x/blob/master/.github/workflows/build-test.yml#L418-L427

But that's okay for now -- I already tested that out when testing my updated instructions for testing GH Actions (😕):
https://github.com/echeran/icu4x/runs/1836595024?check_suite_focus=true#step:11:33
And that's how I got [the result](https://echeran.github.io/icu4x-docs/benchmarks/memory/macos-latest/).

We should "refactor" the path of the performance benchmarks and memory benchmarks URLs. The way you have it (ex: `.../benchmarks/memory/<example>`) is preferable to `.../dev/<component>`.  We can remember that for later when the performance benchmarks get updated to the better tool that uses instructions counts.

2021-02-08 19:44 UTC, merged

2021-02-08 19:49 UTC, gregtatum commented
I filed #483 to handle the file folder refactor. I believe that was in my original list of items, and never followed up with breaking it out.

2021-02-08 19:56 UTC, gregtatum commented
> But that's okay for now -- I already tested that out when testing my updated instructions for testing GH Actions

Thanks for help testing it out. I configured my fork so this... should work now!