Add additional list formatter tests
unicode-org/icu4x pull request #5108
Opened 2024-06-24 10:27 UTC by sffc

See #5107

2024-06-24 15:28 UTC, sffc commented on components/list/src/lazy_automaton.rs
> +#[cfg(all(test, feature = "datagen"))]
We don't feature-gate docs tests but it's fine for unit tests, especially now that there's the lint that prevents features from being spelled wrong

2024-06-24 15:29 UTC, sffc commented on components/list/src/list_formatter.rs
> +        let mut vecdeque = alloc::collections::vec_deque::VecDeque::<u8>::new();
It's not available if the tests are not run with all features

I think our conclusion was that tests without all features could be supported on a best effort basis, which is what I did here

2024-06-24 15:32 UTC, robertbastian commented on components/list/src/lazy_automaton.rs
> +#[cfg(all(test, feature = "datagen"))]
This is an unnecessary change that is unrelated to what this PR says it's doing.

2024-06-24 15:34 UTC, sffc commented on components/list/src/lazy_automaton.rs
> +#[cfg(all(test, feature = "datagen"))]
I changed the title of the PR

2024-06-25 08:20 UTC, robertbastian requested changes
These tests don't add anything, we already have a test that uses fallback with Spanish, and that fails with the setup in https://github.com/unicode-org/icu4x/issues/5107.

2024-06-25 13:56 UTC, closed without merging