More `from_str` cleanups
unicode-org/icu4x pull request #5182
Opened 2024-07-04 13:56 UTC by robertbastian

#4931

2024-07-04 18:00 UTC, sffc submitted a review, later dismissed
You're removing impls from TinyStr wrapper types and instead using direct construction, which seems like a positive change since it avoids an unwrap, despite being more verbose.

2024-07-04 18:02 UTC, robertbastian commented on components/plurals/src/operands.rs
> +impl core::str::FromStr for PluralOperands {
Users can create plural operands from all numeric types as well as fixed decimal, infallibly.

2024-07-05 20:56 UTC, Manishearth approved these changes

2024-07-08 14:23 UTC, robertbastian commented on ffi/ecma402/src/pluralrules.rs
> +        todo!()
what do you want me to do here? I'm tempted to just remove the whole crate

2024-07-08 18:41 UTC, sffc requested changes

2024-07-08 18:41 UTC, sffc commented on ffi/ecma402/src/pluralrules.rs
> +        todo!()
I think endeavor to keep it working. It's not that much code to keep working.

In this case, just change `PluralOperands::from_str` to `FixedDecimal::from_str`.

2024-07-10 16:27 UTC, sffc approved these changes

2024-07-10 16:27 UTC, sffc commented on ffi/ecma402/src/pluralrules.rs
> -        }
Nit: Please restore the test for `to_icu4x_operands`

2024-08-13 16:19 UTC, sffc approved these changes

2024-08-13 16:24 UTC, merged