DurationFormatter: Digital Data Provider
unicode-org/icu4x pull request #5186
Opened 2024-07-05 22:32 UTC by kartva

- based on #5112
- follow up to #5158

Summary of changes:
- add the `DigitalDurationDataV1` data struct to hold digital duration formatter information.

2024-07-06 02:15 UTC, younies requested changes
Could you merge the main branch and include only the provider changes here?

2024-07-07 23:39 UTC, younies commented on components/experimental/src/duration/provider/digital.rs
> +}
```suggestion
pub struct DigitalDurationDataV1<'data> {
   /// TODO: add comments 
    #[cfg_attr(feature = "serde", serde(borrow))]
    separator: Cow<str, 'data>,
    
    /// TODO: add comments
    hour_padding: u8,
}
```

2024-07-07 23:40 UTC, younies commented on components/experimental/src/duration/provider/digital.rs
> +impl<'data> FromStr for DigitalDurationDataV1<'data> {
good job

2024-07-07 23:40 UTC, younies reviewed
Good job , just edit the following comment

2024-07-08 00:02 UTC, kartva commented on components/experimental/src/duration/provider/digital.rs
> +}
Fixed.

2024-07-08 00:05 UTC, kartva commented
The TC39 seems to use the following fields:
- `two_digit_hours`
- `hour_minute_separator`
- `minute_second_separator`

Would it be sensible to instead make the struct use the above fields? It would look like:

```rust
/// A struct containing digital duration data (durationUnit-type-* patterns).
pub struct DigitalDurationDataV1<'data> {
    #[cfg_attr(feature = "serde", serde(borrow))]
    hour_minute_separator: Cow<str, 'data>,
    #[cfg_attr(feature = "serde", serde(borrow))]
    minutes_seconds_separator: Cow<str, 'data>,
    two_digit_hour: bool,
}
```

2024-07-08 14:28 UTC, younies commented
> ```rust
> /// A struct containing digital duration data (durationUnit-type-* patterns).
> pub struct DigitalDurationDataV1<'data> {
>     #[cfg_attr(feature = "serde", serde(borrow))]
>     hour_minute_separator: Cow<str, 'data>,
>     #[cfg_attr(feature = "serde", serde(borrow))]
>     minutes_seconds_separator: Cow<str, 'data>,
>     two_digit_hour: bool,
> ```

Let's postpone this in the next PR where the implementation of the DataProveder. To ensure that we need an extra field or not.

2024-07-08 14:28 UTC, younies approved these changes

2024-07-08 14:29 UTC, merged