Add LocaleData parameter for word/sentence segmenter
unicode-org/icu4x pull request #5214
Opened 2024-07-10 02:14 UTC by makotokato

This is a part of https://github.com/unicode-org/icu4x/issues/3284.

ICU4C has some language break rules for word and sentence segmenter, so this fix adds some rules to ICU4X per locale.

This adds LocaleData argument to all constructors. Since data marker has to remove singleton parameter to support Locale, this happens API breaking change.

2024-07-10 17:14 UTC, sffc commented on provider/data/segmenter/fingerprints.csv
> +segmenter/sentence@2, <total>, 29072B, 2 unique payloads
+1, duplicating the data doesn't scale; having an extension/supplement that contains the diff from the standard payload scales better if many locales have diffs.

2024-07-22 03:46 UTC, makotokato commented on provider/data/segmenter/fingerprints.csv
> +segmenter/sentence@2, <total>, 29072B, 2 unique payloads
@robertbastian, should we keep singleton then should we have both property data into UND? 
The different is property table only (codepoint to property). And rule table for state machine is same.

2024-07-23 23:58 UTC, sffc commented on components/segmenter/src/lib.rs
> +//! let segmenter = WordSegmenter::try_new_auto(&locale!("en").into()).unwrap();
Note: The request was for this to be

`new_auto()`

along with

`try_new_auto_with_options(WordSegmenterOptions::new_with_content_locale(&locale!("en")))`

2024-07-24 00:01 UTC, sffc requested changes
Good that there are cases that work now that failed before. But, the consensus was to implement this while still keeping the previous, infallible, singleton constructors.

2024-07-24 00:01 UTC, sffc commented on components/segmenter/tests/locale.rs
> +fn word_break_with_locale() {
Praise: Glad these cases are working now

2024-07-25 06:21 UTC, makotokato commented
I will update this fix with singleton by adding the difference of property_table to RuleBreakDataV2.

2024-07-25 16:36 UTC, robertbastian commented
Please no force pushes after a started review, [this](https://github.com/unicode-org/icu4x/compare/dd6855da75b2ec0bc7a95cf73f77a3f58e42c570..5adb60e2c2c637a7b22a7e941ee306d58134bbcd) is what the diff looks like now.

2024-07-25 17:31 UTC, makotokato commented
It might be better to add new data marker for locale diff instead, so I will update this

2024-07-25 18:25 UTC, makotokato commented
> Please no force pushes after a started review, [this](https://github.com/unicode-org/icu4x/compare/dd6855da75b2ec0bc7a95cf73f77a3f58e42c570..5adb60e2c2c637a7b22a7e941ee306d58134bbcd) is what the diff looks like now.

I change my idea, not use simply locale, so I would like to reset all.  Should I close this PR, then send new PR instead?

2024-07-26 23:56 UTC, sffc commented
Yes, if the change is sufficiently different, please open a new PR.

2024-07-30 05:28 UTC, makotokato commented
OK. I close this PR, then file new PR

2024-07-30 05:28 UTC, closed without merging

2024-07-30 05:33 UTC, makotokato commented
New PR is https://github.com/unicode-org/icu4x/pull/5318