Breaking: rename VarZeroVecFormatError to ZeroVecInternalFormatError
unicode-org/icu4x pull request #5239
Opened 2024-07-12 21:34 UTC by sffc

Two reasons I'm suggesting this:

1. The error variants are confusing (https://github.com/unicode-org/icu4x/pull/5117)
2. This could let us return this error variant for things other than just VarZeroVec if we add other structures that have their own invariants (maybe ZeroMapSlice, or ZeroSet, or ZeroDefaultVec, https://github.com/unicode-org/icu4x/issues/5139)

2024-07-12 22:19 UTC, Manishearth commented
I'd rather have new error invariants here. VZV is a specific, gnarly format, and getting that wrong is a very particular kind of error that I'd like to see signaled separately.

Also not yet convinced of any of the types in (2).

2024-07-16 10:22 UTC, robertbastian commented on utils/pattern/src/implementations.rs
> +            .map_err(|_| ZeroVecError::ZeroVecInternalFormatError)?;
```suggestion
            .map_err(|_| ZeroVecError::InternalFormat)?;
```

2024-07-16 16:05 UTC, Manishearth requested changes
(see comment above: I disagree with the premise)

2024-07-19 22:05 UTC, sffc commented
In any case I do think the name of this variant is probably worth discussing since I keep seeing people misusing it.

2024-09-17 18:11 UTC, closed without merging