Add neo testing to datetime fixtures
unicode-org/icu4x pull request #5292
Opened 2024-07-24 21:09 UTC by sffc

#1317

2024-07-25 16:20 UTC, robertbastian commented on components/datetime/src/neo_marker.rs
> +    const COMPONENTS: NeoComponents =
pleas merge

2024-07-25 16:24 UTC, robertbastian requested changes

2024-07-25 16:24 UTC, robertbastian commented on components/datetime/src/neo_skeleton.rs
You're adding serde implementations for non-data-structs, just to use them in tests. These should not be on the public API, and should not need to be built outside of tests.

2024-07-25 18:49 UTC, sffc commented on components/datetime/src/neo_skeleton.rs
I added the serde impls on the non-data structs because that's how they were previously in `icu::datetime::options::components`. I do think there's value in having a serde impl for semantic skeleta. Also, as of #5258, the serde impls are already there; I'm just making them better.

2024-07-26 12:34 UTC, robertbastian approved these changes

2024-07-26 19:21 UTC, merged