Include data only in dynamic libraries for Dart
unicode-org/icu4x pull request #5386
Opened 2024-08-16 13:33 UTC by mosuem

Set `if (linkMode == LinkMode.dynamic) 'compiled_data',`, and some cosmetic changes.

2024-08-16 13:34 UTC, mosuem commented on ffi/dart/tool/build_libs.dart
> +    if (linkMode == LinkMode.dynamic) 'compiled_data',
The actual change

2024-08-19 08:22 UTC, robertbastian requested changes
Now that we have feature-passing logic, I'd rather have this be explicitly decided by the caller than derived from the linking type.

2024-08-19 10:26 UTC, robertbastian commented on ffi/dart/tool/build_libs.dart
> +  ].join(',');
nit: spread the `cargoFeatures` in here

2024-08-19 11:20 UTC, robertbastian commented on ffi/dart/tool/build_libs.dart
> +    '--features=${[...features, ...cargoFeatures].join(',')}',
cargo features and features are the same thing, they should be merged earlier

2024-08-19 13:39 UTC, robertbastian approved these changes
Also please merge this into main

2024-08-19 13:39 UTC, merged