DurationFormatter: Handle zero durations correctly
unicode-org/icu4x pull request #5432
Opened 2024-08-22 03:42 UTC by kartva

Format zero durations correctly: with no sign. (Previously it was possible to create negative zero durations)

2024-08-22 14:12 UTC, younies reviewed
Fix CI

2024-08-26 18:35 UTC, sffc reviewed
The spec requires formatting of negative 0 if there is a 0 unit at the front of a duration that is negative otherwise; for example, "-PT1M" formatted with hourDisplay: "always" should render "-0 hours, 1 minute". Does this PR handle that case? Maybe add a test?

2024-09-04 05:37 UTC, younies commented on components/experimental/src/duration/format.rs
> +    }
add a test case to for 
` -0 yrs, 1 month`

2024-09-04 05:37 UTC, younies requested changes
add a test case to for
` -0 yrs, 1 month`

2024-09-09 13:16 UTC, younies approved these changes

2024-09-09 13:17 UTC, merged

2024-09-09 16:24 UTC, sffc reviewed
Lgtm