Split specific names map
unicode-org/icu4x pull request #5762
Opened 2024-11-01 14:57 UTC by robertbastian

This is actually only a 2.5% data saving 🤷

2024-11-04 17:24 UTC, Manishearth approved these changes

2024-11-04 22:59 UTC, sffc requested changes
It makes some locales bigger because now you have 4 ZeroMaps instead of 2 in the fields of the formatter.

Can you write this such that we don't have more ZeroMaps?

This directly impacts memory use over FFI.

2024-11-05 08:49 UTC, robertbastian commented
> Can you write this such that we don't have more ZeroMaps?

No, that's the purpose of this PR.

Don't we have size tests for neo formatter? They seem to be unimpacted.

2024-11-05 17:35 UTC, robertbastian commented
* This increases stack size, and heap size in FFI
* This makes adding more zone variants a data-breaking change in the future
* This slightly decreases data size

Conclusion: don't merge, maybe investigate other models in the future (@sffc, @robertbastian)

2024-11-05 17:35 UTC, closed without merging