Bump MSRV to 1.80
unicode-org/icu4x pull request #5934
Opened 2024-12-19 22:31 UTC by Manishearth

2024-12-19 22:53 UTC, Manishearth commented
n.b. I kept the rustdoc nightly and the LLVM nightly separate to keep an indicator that they _can_ be separate. However I could homogenize them if desired.

2024-12-21 04:09 UTC, sffc requested changes
Let's wait on https://github.com/unicode-org/icu4x/issues/5935 first. Sorry.

2024-12-21 04:12 UTC, sffc commented
There's a lot of good stuff in here. I think we can get to Rust 1.75 at least, and maybe Rust 1.76, without bumping LLVM. It sadly doesn't get us `slice_at_checked`, but I agree that if we're going to be upgrading MSRV, doing so at the major version boundary seems like a good call.

That said, if there isn't anything in 1.76 that we care about, then we should lean toward lower MSRV when possible.

2024-12-21 04:15 UTC, sffc commented
Also, for the specific problem of `split_at_checked`, I previously found that the following code compiles to exactly the same assembly.

```rust
if i <= my_slice.len() {
    Some(my_slice.split_at(i))
} else {
    None
}
```

In other words, the bounds check inside `split_at` goes away once the code is inlined.

So, although I would be very happy to use `split_at_checked`, I'm not convinced it is a strong enough reason to break Xcode for the next 9 months.

2024-12-23 18:50 UTC, Manishearth commented
> Also, for the specific problem of `split_at_checked`, I previously found that the following code compiles to exactly the same assembly.

Yeah I proposed this before, I don't recall what Henri felt about that. I'll comment on the other issue.

2024-12-26 23:07 UTC, sffc commented
> I actually feel that the reason of "we should start 2.0 with a relatively upgraded rustc so that _future_ upgrades are rarer" is a more compelling reason than this one API.

I agree with this and am okay temporarily relaxing the Xcode constraint in order to reduce the number of MSRV changes in the 2.x stream.

> I consider the ability to run a pair of niche FFI tests on a default Mac install to be negligible in value.

Discussed in #5945; it's about how a prototypical ICU4X iOS developer, one who is expected to care about binary size, should use ICU4X, not just "running niche FFI tests on a default Mac install."

2025-01-07 12:28 UTC, robertbastian commented
I will be pushing for 1.81 as soon as our policy allows (in six weeks), as that contains `core::error` and will let us get rid of most our `std` features. Might want to do that now already if we're trying to minimize the number of MSRV bumps after release.

2025-01-07 13:02 UTC, Manishearth commented
@sffc Perhaps we can merge this PR now to at least set the stage for that upgrade? This PR is not against any current policy about Rust versions so I do not perceive it as needing TC approval.

2025-01-07 13:03 UTC, Manishearth commented
And yes, I would be in favor of getting rid of our std features, which we won't be able to do as easily post 2.0.

2025-01-09 01:19 UTC, sffc approved these changes
Wait, current stable Rust is 1.83, so 1.80 is not compatible even with the TC-exception portion of the policy.

My comment will be invalid tomorrow, and I approve making an exception here because I want a higher MSRV in 2.0 so we don't have to change it as much later.

2025-01-09 01:25 UTC, Manishearth commented
> Wait, current stable Rust is 1.83, so 1.80 is not compatible even with the TC-exception portion of the policy

Oh, yes, I should have called that out: this entire thing was assuming that we'd not be releasing 2.0 before the second week of January, which seemed rather certain. Sorry.

(The LLVM upgrade is required by far older rustc, I think from testing the requirement, or at least the incompatability, kicks in at around 1.74 or so, which is N-9)

2025-01-09 01:26 UTC, merged