Stop accepting underscores as subtag separators
unicode-org/icu4x pull request #5943
Opened 2024-12-20 23:42 UTC by Manishearth

Part of #3989

2025-01-13 22:55 UTC, sffc reviewed
Did we agree to do this?

2025-01-13 22:57 UTC, Manishearth commented
I don't recall if there was explicit agreement, we decided this was work we would need to do on our side to support ECMA.

I don't think there was any dissent towards landing this.

2025-01-13 23:00 UTC, sffc commented
@zbraniecki ?

2025-01-14 01:18 UTC, zbraniecki commented
Yeah, I'm ok with it. It actually solves the ECMA-402 problem by reversing the cohort that has to workaround it. If you want to support `_`, then convert them before passing to icu::Locale.

2025-01-14 01:19 UTC, zbraniecki submitted a review, later dismissed

2025-01-14 01:57 UTC, sffc submitted a review, later dismissed

2025-01-14 09:51 UTC, robertbastian requested changes
The data diff should not be there. I believe it's caused by the icuexport filenames using underscores, which needs a workaround in the source data provider.

2025-01-14 10:03 UTC, robertbastian approved these changes

2025-01-14 15:45 UTC, merged

2025-01-15 14:29 UTC, linusg commented
Is it intentional that `cmn-hans-cn-t-ca-u-ca-x_t-u` (from https://github.com/tc39/test262/blob/a37cb9c206bf544837b69170bb99a205a8635a8d/harness/testIntl.js#L240) is still accepted as valid after this change? This means that implementors of ECMA-402 will still have to do a manual check for underscores.

2025-01-15 14:48 UTC, robertbastian commented
It is not. I have reproduced this and will fix.

2025-01-15 20:57 UTC, nciric reviewed
I agree, we don't need to carry _ compatibility like ICU4C does. One can always g/_/-/s before constructing Locale.