Update failing generated-readme-check error message
unicode-org/icu4x pull request #641
Opened 2021-04-13 16:48 UTC by gregtatum

I was somewhat confused when this failed for me locally. I updated the error message a bit to make it clearer what actions needed to be taken. Here is the output on my machine:

![image](https://user-images.githubusercontent.com/1588648/114590031-ded75180-9c4d-11eb-8467-61f6bb7f20d4.png)

The duckscript syntax is weird, as it was the only way I could do multi-line strings in any sane way.

2021-04-13 16:55 UTC, Manishearth submitted a review, later dismissed

2021-04-13 17:02 UTC, sffc requested changes

2021-04-13 17:02 UTC, sffc commented on Makefile.toml
> +        array_push ${msg} "${output.stdout}"
```suggestion
        array_push ${msg} "A README.md file is out-of-sync with lib.rs!
        array_push ${msg} ""
        array_push ${msg} "If you modified a lib.rs file, please run `cargo make generate-readmes`. If you edited a"
        array_push ${msg} "README.md file directly, please also update the corresponding lib.rs."
        array_push ${msg} ""
        array_push ${msg} "The modified files were:"
        array_push ${msg} "${output.stdout}"
```

2021-04-22 16:36 UTC, Manishearth approved these changes

2021-04-22 16:58 UTC, echeran approved these changes
LGTM

2021-04-22 17:50 UTC, sffc submitted a review, later dismissed

2021-04-22 17:50 UTC, dminor approved these changes

2021-04-22 18:09 UTC, dminor approved these changes

2021-04-22 20:20 UTC, sffc approved these changes

2021-04-26 22:07 UTC, merged