Split DateTimeFormat keys
unicode-org/icu4x pull request #774
Opened 2021-06-08 20:46 UTC by zbraniecki

Fixes #257

2021-06-09 05:56 UTC, sffc reviewed
> @sffc does it look generally like the right direction to you?

Yes, this looks like what I had in mind!

> How should I handle StructProvider in such a composed bound scenario?

I would think that in order to make a StructProvider return multiple types of structs, one would have two StructProvider instances and then tie them together with another class that delegates to one or the other.  Perhaps we could make a helper macro for that.

2021-06-09 05:56 UTC, sffc commented on components/datetime/src/datetime.rs
> +        let symbols = DataPayload::from_owned(symbols_data.get().clone());
Suggestion: You can delete this TODO now and just pass the `symbols_data` argument straight through. :smiley:

2021-06-10 17:53 UTC, zbraniecki commented
This is now ready for review.

It seems to give a 5-8% win in `cargo criterion` bench for me. I'm not sure why tbh because we still load both for every `DateTimeFormat` instance, but I assume it opens up ability to later implement logic to only load symbols if needed, right?

2021-06-10 18:51 UTC, sffc requested changes

2021-06-10 18:51 UTC, sffc commented on components/datetime/src/datetime.rs
> +        let symbols = DataPayload::from_owned(symbols_data.get().clone());
Actually, ping on this suggestion.

2021-06-10 22:14 UTC, sffc approved these changes

2021-06-11 19:27 UTC, gregtatum approved these changes
LGTM!

2021-06-11 19:28 UTC, merged