Add benchmarks for the WASM FFI layer
unicode-org/icu4x pull request #784
Opened 2021-06-09 23:46 UTC by shadaj

Also fixes FixedDecimalFormat to consider the options parameter

2021-06-10 02:31 UTC, Manishearth submitted a review, later dismissed

2021-06-10 09:04 UTC, sffc requested changes

2021-06-10 09:04 UTC, sffc commented on ffi/wasm/bench/package.json
> +{
Suggestion: please add a `npm` task here so that one can run something like `npm run bench`.

2021-06-17 17:14 UTC, Manishearth approved these changes

2021-06-17 17:14 UTC, sffc approved these changes

2021-06-17 17:15 UTC, merged